apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p5
  template:
    metadata:
      labels:
        app: p5
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p5
        ports:
        - containerPort: 80
